# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is used to configure the GenAI provider matching rules and estimated pricing.
# The rules define how to map model names to providers and calculate token costs.

providers:
  - provider: openai
    base-url:
    prefix-match:
      - gpt
    models:
      - name: gpt-4.1-2025-04-14
        input-cost-per-m: 10000
        output-cost-per-m: 10000
      - name: gpt-4.1
        input-cost-per-m: 500
        output-cost-per-m: 500

  - provider: anthropic
    base-url:
    prefix-match:
      - claude
    models:
      - name: claude-3-7-sonnet-20250219-thinking
        input-cost-per-m: 10000
        output-cost-per-m: 10000

  - provider: gemini
    base-url:
    prefix-match:
      - gemini

  - provider: mistral
    base-url:
    prefix-match:
      - mistral-

  - provider: groq
    base-url:
    prefix-match:
      - llama-3

  - provider: deepseek
    base-url:
    prefix-match:
      - deepseek

  - provider: bytedance
    base-url:
    prefix-match:
      - doubao

  - provider: zhipu_ai
    base-url:
    prefix-match:
      - glm

  - provider: alibaba
    base-url:
    prefix-match:
      - qwen

  - provider: tencent
    base-url:
    prefix-match:
      - hunyuan

  - provider: moonshot
    base-url:
    prefix-match:
      - kimi

  - provider: minimax
    base-url:
    prefix-match:
      - minimax

  - provider: ollama
    base-url:
    prefix-match:
      - ollama
    models:
      - name: ollama
        input-cost-per-m: 1
        output-cost-per-m: 1

  - provider: azure_openai
    base-url:
    prefix-match:
      - azure